name: besu
title: Besu 
base: core24
adopt-info: besu
summary: Besu - Hyperledger Ethereum client.
license: GPL-3.0-with-GCC-exception
contact: info@dwellir.com
issues: https://github.com/dwellir-public/snap-besu/issues
source-code: https://github.com/dwellir-public/snap-besu
website: https://www.dwellir.com
grade: stable
confinement: strict

platforms:
  amd64:
  arm64:
  armhf:

description: |
  Hyperledger Besu is an Ethereum client designed to be enterprise-friendly for both public and private permissioned network use cases, with an extractable EVM implementation. 
  It can also be run on test networks such as Holesky and Sepolia. Hyperledger Besu includes several consensus algorithms including Proof of Stake, Proof of Work, and Proof of Authority (IBFT 2.0, QBFT, and Clique). Its comprehensive permissioning schemes are designed specifically for use in a consortium environment.

parts:
  besu:
    after: [utils]
    plugin: nil
    build-packages: 
      - openjdk-21-jdk-headless
    source: https://github.com/hyperledger/besu.git
    source-tag: 24.7.0
    stage-packages:
      - openjdk-21-jre-headless

    override-pull: |
      craftctl default
      craftctl set version="24.7.0-$(git rev-parse --short HEAD)"

    override-build: |
      echo "BEGIN BUILD OF BESU - gradlew"

      echo "Extracting potential https_proxy and/pr http_proxy as needed when building with Canonical buildfarm"
      PROXY_OPTS=$($SNAPCRAFT_STAGE/utils/getproxy.sh)
      # Include the -Djava.net.useSystemProxies=true for builds with Canonical launchpad.
      GRADLE_OPTS="-Djava.net.useSystemProxies=true $PROXY_OPTS" ./gradlew --no-daemon installDist
      
      echo "COMPLETED BUILD OF BESU - gradlew"

    override-stage: |
      printenv
      mkdir -p "${CRAFT_PRIME}"/bin
      cp ${CRAFT_PART_BUILD}/build/install/besu/bin/besu ${SNAPCRAFT_PRIME}/bin/besu
      cp ${CRAFT_PART_BUILD}/build/install/besu/bin/evmtool ${SNAPCRAFT_PRIME}/bin/evmtool
      cp -r ${CRAFT_PART_BUILD}/build/install/besu/lib ${SNAPCRAFT_PRIME}/
      craftctl default

  wrappers:
    plugin: dump
    source-type: local
    source: .
    stage:
      - wrappers/


  utils:
    plugin: dump
    source: .
    stage:
      - utils/


apps:
  besu-daemon:
    command: wrappers/start-besu.bash
    daemon: simple
    install-mode: disable
    refresh-mode: endure
    restart-condition: never
    plugs:
      - network
      - network-bind
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      JAVA_HOME: $SNAP/usr/lib/jvm/java-21-openjdk-amd64/
